"""Update config prompts with per-frame descriptions."""
import json, glob, os

CONFIG_DIR = r"C:\dev\loracomp3\data\configs"

new_prompts = {
    1: "sprt4x4, Generate 4x4 sprite sheet: a fighter in idle and walking animation. Frame 1: fighting stance fists raised. Frame 2: slight weight shift. Frame 3: fists up guard position. Frame 4: weight on back foot. Frame 5: stepping forward left foot out. Frame 6: mid-stride arms swinging. Frame 7: full stride right foot forward. Frame 8: completing step cycle. Frame 9: walking forward left step. Frame 10: mid-walk arms back. Frame 11: right foot stepping. Frame 12: walk cycle completing. Frame 13: walking backward right foot back. Frame 14: stepping back weight shifting. Frame 15: left foot pulling back. Frame 16: returning to stance.",

    2: "sprt4x4, Generate 4x4 sprite sheet: a fighter running then diving into a combat roll. Frame 1: running left foot forward leaning ahead. Frame 2: full sprint right leg pushing off. Frame 3: mid-run airborne between strides. Frame 4: sprint landing right foot. Frame 5: decelerating leaning forward. Frame 6: bending down hands reaching to ground. Frame 7: hands on ground knees bending. Frame 8: tucking into roll head going down. Frame 9: upside down mid-roll legs over head. Frame 10: rolling over back curled up. Frame 11: coming out of roll on side. Frame 12: on ground pushing up. Frame 13: crouched on all fours. Frame 14: hands pushing off ground. Frame 15: rising to standing. Frame 16: back to upright stance.",

    3: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing left hook then right hook punches. Frame 1: guard stance fists up. Frame 2: left shoulder rotating back for wind-up. Frame 3: left arm extending forward in hook. Frame 4: left fist at full extension striking. Frame 5: left arm following through past target. Frame 6: pulling left arm back. Frame 7: returning to guard. Frame 8: squared up stance. Frame 9: right shoulder dropping for wind-up. Frame 10: right arm swinging forward. Frame 11: right hook connecting at full extension. Frame 12: right fist past target following through. Frame 13: body rotating with punch momentum. Frame 14: pulling right arm back. Frame 15: recovering balance. Frame 16: back to guard stance.",

    4: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing a rotating hook punch then quick right hook. Frame 1: guard stance. Frame 2: body turning left for wind-up. Frame 3: torso rotating arm coming around. Frame 4: hook punch at full extension body twisted. Frame 5: following through past center. Frame 6: arm wrapping around. Frame 7: pulling back recovering. Frame 8: resetting stance. Frame 9: quick right hand cocking back. Frame 10: right arm shooting forward. Frame 11: right hook landing. Frame 12: fist at full extension. Frame 13: following through body leaning. Frame 14: pulling back. Frame 15: recovering balance. Frame 16: returning to guard.",

    5: "sprt4x4, Generate 4x4 sprite sheet: a fighter throwing four rapid alternating punches. Frame 1: guard stance fists up. Frame 2: left jab extending forward. Frame 3: left fist at full extension. Frame 4: left arm retracting right loading. Frame 5: right cross shooting forward. Frame 6: right fist at full extension body rotated. Frame 7: right retracting left loading. Frame 8: left hook swinging wide. Frame 9: left hook at full extension. Frame 10: left retracting. Frame 11: right hook winding up. Frame 12: right hook at full extension. Frame 13: right following through. Frame 14: pulling both arms back. Frame 15: recovering to center. Frame 16: back to guard stance.",

    6: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing a knee strike then spinning roundhouse kick. Frame 1: fighting stance. Frame 2: shifting weight to back leg. Frame 3: knee driving upward. Frame 4: knee at peak height. Frame 5: knee at maximum impact point. Frame 6: leg dropping down. Frame 7: foot returning to ground. Frame 8: resetting stance. Frame 9: stepping forward to wind up kick. Frame 10: body turning back to camera. Frame 11: kicking leg chambering. Frame 12: leg extending out in roundhouse. Frame 13: leg at full extension horizontal. Frame 14: kick following through. Frame 15: leg coming down. Frame 16: landing back in stance.",

    7: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing a spinning aerial kick. Frame 1: fighting stance. Frame 2: stepping forward planting foot. Frame 3: jumping off ground body rising. Frame 4: airborne body turning knees tucked. Frame 5: mid-air spinning back to camera. Frame 6: kicking leg extending in mid-air. Frame 7: full spin kick leg at maximum extension. Frame 8: leg extended horizontal in air. Frame 9: following through in air. Frame 10: body rotating past kick. Frame 11: legs coming together descending. Frame 12: approaching ground. Frame 13: landing on one foot. Frame 14: other foot touching down. Frame 15: absorbing landing bent knees. Frame 16: recovering to stance.",

    8: "sprt4x4, Generate 4x4 sprite sheet: a fighter falling backward then getting back up. Frame 1: standing being pushed back. Frame 2: staggering backward arms out. Frame 3: leaning far back off balance. Frame 4: falling backward legs leaving ground. Frame 5: mid-fall nearly horizontal. Frame 6: hitting the ground on back. Frame 7: flat on ground arms spread. Frame 8: lying on ground motionless. Frame 9: lying on ground starting to move. Frame 10: rolling onto side. Frame 11: pushing up with arms on ground. Frame 12: on hands and knees. Frame 13: one knee up pushing off ground. Frame 14: rising to crouch. Frame 15: straightening up. Frame 16: back to standing stance.",

    9: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing a capoeira spinning kick. Frame 1: fighting stance leaning forward. Frame 2: stepping into spin weight on front foot. Frame 3: body turning back starting to face away. Frame 4: back to camera arms wide for balance. Frame 5: spinning kicking leg lifting. Frame 6: leg sweeping around horizontally. Frame 7: kick at full extension mid-spin. Frame 8: leg sweeping past high point. Frame 9: continuing rotation leg coming around. Frame 10: facing forward again leg still extended. Frame 11: kicking leg coming down. Frame 12: leg dropping toward ground. Frame 13: foot touching down. Frame 14: recovering balance. Frame 15: stepping back. Frame 16: returning to fighting stance.",

    10: "sprt4x4, Generate 4x4 sprite sheet: a fighter getting hit then blocking. Frame 1: standing getting hit in head snapping back. Frame 2: head recoiling from hit. Frame 3: recovering from head hit. Frame 4: returning to stance after head hit. Frame 5: getting hit in upper body leaning back. Frame 6: body recoiling from medium hit. Frame 7: absorbing the hit. Frame 8: recovering from body hit. Frame 9: getting punched in stomach bending forward. Frame 10: doubled over from stomach hit. Frame 11: recovering straightening up. Frame 12: returning to stance. Frame 13: raising both arms up in block position. Frame 14: arms crossed in front for defense. Frame 15: holding block stance. Frame 16: lowering arms from block.",

    11: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing a left roundhouse kick then right push kick. Frame 1: stance left leg chambering up. Frame 2: left knee rising to hip height. Frame 3: left leg extending in roundhouse. Frame 4: left kick at full extension. Frame 5: left leg sweeping through. Frame 6: left leg retracting. Frame 7: left foot returning to ground. Frame 8: resetting stance. Frame 9: shifting weight for right kick. Frame 10: right knee chambering. Frame 11: right leg thrusting forward in push kick. Frame 12: right foot at full extension pushing. Frame 13: right kick following through. Frame 14: right leg pulling back. Frame 15: right foot coming down. Frame 16: returning to stance.",

    12: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing knee jabs then an uppercut. Frame 1: stance stepping forward. Frame 2: right knee driving up. Frame 3: knee at peak height. Frame 4: knee dropping left knee rising. Frame 5: left knee jabbing upward. Frame 6: alternating knee at peak. Frame 7: knee coming down stepping forward. Frame 8: loading right knee again. Frame 9: right knee driving up higher. Frame 10: knee at maximum height. Frame 11: planting foot winding up fist. Frame 12: crouching low for uppercut. Frame 13: fist driving upward from below. Frame 14: uppercut at full extension arm overhead. Frame 15: arm coming down. Frame 16: recovering to stance.",

    13: "sprt4x4, Generate 4x4 sprite sheet: a fighter performing a punch to elbow combo. Frame 1: guard stance stepping in. Frame 2: left jab shooting forward. Frame 3: lunging forward with right cross. Frame 4: deep lunge double punch both arms extended. Frame 5: pulling back from lunge. Frame 6: right cross retracting. Frame 7: body rotating for elbow. Frame 8: spinning elbow strike arm bent. Frame 9: elbow at impact point. Frame 10: following through spinning. Frame 11: quick jab snapping out. Frame 12: another short punch. Frame 13: elbow snapping with tight turn. Frame 14: body fully rotated. Frame 15: wide step back recovering. Frame 16: returning to fighting stance.",
}

updated = 0
for f in sorted(glob.glob(os.path.join(CONFIG_DIR, "sheet_*.json"))):
    with open(f) as fh:
        d = json.load(fh)
    idx = d["sheet_index"]
    if idx in new_prompts:
        d["prompt"] = new_prompts[idx]
        with open(f, "w") as fh:
            json.dump(d, fh, indent=4)
        print(f"Sheet {idx:02d}: updated ({len(new_prompts[idx])} chars)")
        updated += 1

print(f"\n{updated} configs updated")
